version: '3.7'

services:
  # Backend Service 
  graphql-api:
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db
    networks:
      - frontend
      - backend  

  # Frontend Service 
  app-client:
    build:
      context: app
      dockerfile: Dockerfile
      args:
        API_BASE_URL: http://127.0.0.1:8080/graphql
    ports:
      - "9090:80"
    restart: always
    depends_on:
      - graphql-api
    networks:
      - frontend  

  db:
    image: mysql:5.7
    container_name: trk_mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: tracker_dev
      MYSQL_USER: trk_dev
      MYSQL_PASSWORD: pass123
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PORT: 3307
    expose: 
      - "3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend  
  
# Volumes
volumes:
  db-data:

# Networks to be created to facilitate communication between containers
networks:
  backend:
  frontend: